version: 2.1

jobs: # a basic unit of work in a run
  findSchemeName:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: Find Available scheme names
          command: xcodebuild -list
  test: # your job name
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme Core

  build: 
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: 
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip build/Release/circleci-demo-macos.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: app.zip
          destination: app
          
workflows:
  test_build:
    jobs:
      - findSchemeName
      - test
      - build:
          requires:
            - test
