version: 2.1
jobs:
  build:
    macos:
      xcode: 14.1.0 # Specify the Xcode version to use
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello Deblina! Welcome to CircleCI'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^'
