version: 2.1
jobs:
  build:
    macos:
      xcode: 14.1.0 # Specify the Xcode version to use
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
